# Generated by Django 2.1.2 on 2018-10-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratuszBudowa', models.DateTimeField(blank=True, null=True)),
                ('koszaryBudowa', models.DateTimeField(blank=True, null=True)),
                ('drogiBudowa', models.DateTimeField(blank=True, null=True)),
                ('kopalniaBudowa', models.DateTimeField(blank=True, null=True)),
                ('elektrowniaBudowa', models.DateTimeField(blank=True, null=True)),
                ('farmyBudowa', models.DateTimeField(blank=True, null=True)),
                ('cityOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
