# Generated by Django 2.1.2 on 2018-10-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityowned',
            name='cityName',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='drogi',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='elektrownia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='farmy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='kopalnia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='koszary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='pozX',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='pozY',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='ratusz',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='ratuszBudowaTrwa',
            field=models.IntegerField(default=0),
        ),
    ]
