# Generated by Django 2.1.2 on 2018-11-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0002_auto_20181027_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityowned',
            name='drogiBudowaTrwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='elektrowniaBudowaTrwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='farmyBudowaTrwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='hinfantry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='htanks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='infantry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='kopalniaBudowaTrwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='koszaryBudowaTrwa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='ltanks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='motorized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='planes',
            field=models.IntegerField(default=0),
        ),
    ]
