# Generated by Django 2.1.2 on 2018-11-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0004_cityowned_is_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='HInfantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=30)),
                ('attack', models.IntegerField(default=30)),
                ('speed', models.IntegerField(default=10)),
                ('capacity', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='HTanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=200)),
                ('attack', models.IntegerField(default=100)),
                ('speed', models.IntegerField(default=30)),
                ('capacity', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Infantry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=10)),
                ('attack', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=20)),
                ('capacity', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='LTanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=100)),
                ('speed', models.IntegerField(default=80)),
                ('capacity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motorized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=50)),
                ('attack', models.IntegerField(default=50)),
                ('speed', models.IntegerField(default=100)),
                ('capacity', models.IntegerField(default=250)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=200)),
                ('speed', models.IntegerField(default=300)),
                ('capacity', models.IntegerField(default=150)),
            ],
        ),
    ]
