# Generated by Django 2.1.2 on 2018-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0005_hinfantry_htanks_infantry_ltanks_motorized_planes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionSpeed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceProduction', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceProduction', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceProduction', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionSpeed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionSpeed', models.IntegerField(default=1)),
                ('lvlToUnlockPlanes', models.IntegerField(default=25)),
                ('lvlToUnlockHtanks', models.IntegerField(default=20)),
                ('lvlToUnlockLtanks', models.IntegerField(default=15)),
                ('lvlToUnlockMotorized', models.IntegerField(default=10)),
                ('lvlToUnlockHinfantry', models.IntegerField(default=5)),
            ],
        ),
        migrations.AddField(
            model_name='cityowned',
            name='electrity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='hinfantrySupport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='htanksSupport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='infantrySupport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='ltanksSupport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='motorizedSupport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='ore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='planesSupport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='population',
            field=models.IntegerField(default=100),
        ),
    ]
