# Generated by Django 2.1.2 on 2018-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0006_auto_20181124_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='barracks',
            name='pointsPerLvl',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cityowned',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='farms',
            name='pointsPerLvl',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='housing',
            name='pointsPerLvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mines',
            name='pointsPerLvl',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='powerplant',
            name='pointsPerLvl',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='roads',
            name='pointsPerLvl',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='townhall',
            name='pointsPerLvl',
            field=models.IntegerField(default=10),
        ),
    ]
