# Generated by Django 2.1.2 on 2018-11-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_auto_20181125_1448'),
        ('cityMap', '0007_auto_20181124_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityowned',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainPage.Server'),
        ),
    ]
