# Generated by Django 2.1.2 on 2018-12-01 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
