# Generated by Django 2.1.2 on 2018-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allianceinvite',
            name='have_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleraport',
            name='have_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpraport',
            name='have_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialresourceraport',
            name='have_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traderaport',
            name='have_seen',
            field=models.BooleanField(default=False),
        ),
    ]
