# Generated by Django 2.1.2 on 2018-12-01 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cityMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive', models.DateTimeField(default=django.utils.timezone.now)),
                ('send', models.DateTimeField(default=django.utils.timezone.now)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackerwm', to='cityMap.CityOwned')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenderwm', to='cityMap.CityOwned')),
            ],
        ),
    ]
