# Generated by Django 2.1.2 on 2018-12-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='hinfantry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attack',
            name='htanks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attack',
            name='infantry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attack',
            name='ltanks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attack',
            name='motorized',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attack',
            name='planes',
            field=models.IntegerField(default=0),
        ),
    ]
