# Generated by Django 2.1.2 on 2018-12-11 15:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cityMap', '0001_initial'),
        ('worldMap', '0002_auto_20181205_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive', models.DateTimeField(default=django.utils.timezone.now)),
                ('send', models.DateTimeField(default=django.utils.timezone.now)),
                ('infantry', models.IntegerField(default=0)),
                ('hinfantry', models.IntegerField(default=0)),
                ('planes', models.IntegerField(default=0)),
                ('ltanks', models.IntegerField(default=0)),
                ('htanks', models.IntegerField(default=0)),
                ('motorized', models.IntegerField(default=0)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenderswm', to='cityMap.CityOwned')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportwm', to='cityMap.CityOwned')),
            ],
        ),
    ]
