# Generated by Django 2.1.2 on 2018-10-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_auto_20181025_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('playerAmount', models.IntegerField(max_length=25)),
                ('speed', models.FloatField(max_length=10)),
                ('multiplicationValue', models.FloatField(max_length=10)),
            ],
        ),
    ]
