# Generated by Django 2.1.2 on 2018-11-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alliance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alliance.Alliance'),
        ),
    ]
