# Generated by Django 2.1.2 on 2018-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0009_auto_20181124_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='nextVillageId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='server',
            name='nextVillageX',
            field=models.IntegerField(default=1575),
        ),
        migrations.AddField(
            model_name='server',
            name='nextVillageY',
            field=models.IntegerField(default=1175),
        ),
    ]
