# Generated by Django 2.1.2 on 2018-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0010_auto_20181125_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villageX', models.IntegerField(default=1575)),
                ('villageY', models.IntegerField(default=1175)),
            ],
        ),
    ]
