# Generated by Django 2.1.2 on 2018-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0011_citypositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='until_premium',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
