# Generated by Django 2.1.3 on 2018-11-23 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceOneMonth', models.FloatField()),
                ('priceHalfYear', models.FloatField()),
                ('priceYear', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tranzakcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfPremium', models.IntegerField(default=1)),
                ('buyingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
