# Generated by Django 2.1.2 on 2018-12-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
